### PR TITLE
Fix debugging of contract creation

### LINKED ISSUE #37: could not debug contract created by contract
project: https://github.com/slepher/truffle_test

truffle version: v4.1.0

reproduce:
`truffle develop`
`migrate`
`StorageManager.deployed().then((instance) => {return instance.createStorage()});`
`debug <txid>`

> [ slepher@issac ~/project/truffle_test (master) ] truffle develop
> Connected to existing Truffle Develop session at http://localhost:9545/
> 
> truffle(develop)> migrate
> Compiling ./contracts/Migrations.sol...
> Compiling ./contracts/SimpleStorage.sol...
> Compiling ./contracts/StorageManager.sol...
> Writing artifacts to ./build/contracts
> 
> Using network 'develop'.
> 
> Running migration: 1_initial_migration.js
>   Deploying Migrations...
>   ... 0xbb145925d2348100bcaca3ed4782c6e65fe010c71525367609e57df64f77aabf
>   Migrations: 0x9efec315e368e8812025b85b399a69513cd0e716
> Saving successful migration to network...
>   ... 0x834bf7895ffbaa129edd5925cae516d4966677bfebc1568dc56fc1ca9018e1a0
> Saving artifacts...
> Running migration: 2_deploy_storage.js
>   Deploying StorageManager...
>   ... 0x9e1b3f5d67b91bb44a8ecc4223ad2be114cb1d6e6719cb17d7c3ec6baa933a36
>   StorageManager: 0xd5e8aa91bda51688e6f3de82e52fb38e35298515
>   Deploying SimpleStorage...
>   ... 0xcf719e6cfc842b2680e2ef347e94014d380703bbed7503e18c7109ed940a8d0f
>   SimpleStorage: 0xa509542ada3196a38bd6fd03b253547ee09220c4
> Saving successful migration to network...
>   ... 0x2b63a20cb4c69f0caa8d9abcb5e2859058fd9b346333a9f684c959a2d3ce7619
> Saving artifacts...
> truffle(develop)> StorageManager.deployed().then((instance) => {return instance.createStorage()});
> { tx: '0xf5775c50c8b3bfdc449a3cff765aa2cc78e325e887ba047939a836d84e985372',
>   receipt:
>    { transactionHash: '0xf5775c50c8b3bfdc449a3cff765aa2cc78e325e887ba047939a836d84e985372',
>      transactionIndex: 0,
>      blockHash: '0xaff312633613d4cdd6904281f81156c12cc03e2f65e31f23d429a2ad20fe169a',
>      blockNumber: 65,
>      gasUsed: 201088,
>      cumulativeGasUsed: 201088,
>      contractAddress: null,
>      logs: [],
>      status: '0x01',
>      logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000' },
>   logs: [] }
> truffle(develop)> debug 0xf5775c50c8b3bfdc449a3cff765aa2cc78e325e887ba047939a836d84e985372
> 
> Gathering transaction data...
> 
> Addresses affected:
>  0x96738907596faa777927b47dd8ce1a385fa8ebb4 - SimpleStorage
>  0xd5e8aa91bda51688e6f3de82e52fb38e35298515 - StorageManager
> 
> Commands:
> (enter) last command entered (step next)
> (o) step over, (i) step into, (u) step out, (n) step next
> (;) step instruction, (p) print instruction, (h) print this help, (q) quit
> (b) toggle breakpoint, (c) continue until breakpoint
> (+) add watch expression (`+:<expr>`), (-) remove watch expression (-:<expr>)
> (?) list existing watch expressions
> (v) print variables and values, (:) evaluate expression - see `v`
> 
> 
> StorageManager.sol:
> 
> 3: import "./SimpleStorage.sol";
> 4:
> 5: contract StorageManager {
>    ^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> debug(develop:0xf5775c50...)> o
> 
> StorageManager.sol:
> 
>  9:   uint public afterCounter;
> 10:
> 11:   function createStorage() public returns(uint) {
>       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> debug(develop:0xf5775c50...)> o
> 
> StorageManager.sol:
> 
> 10:
> 11:   function createStorage() public returns(uint) {
> 12:       counter = counter + 1;
>                               ^
> 
> debug(develop:0xf5775c50...)> o
> 
> StorageManager.sol:
> 
> 11:   function createStorage() public returns(uint) {
> 12:       counter = counter + 1;
> 13:       simple = new SimpleStorage();
>                    ^^^^^^^^^^^^^^^^^^^
> 
> debug(develop:0xf5775c50...)> o
> redux-saga error: uncaught at saga
> at saga
>  at saga
>  at takeEvery
>  at tickSaga
>  TypeError: Cannot convert undefined or null to object
>     at entries (<anonymous>)
>     at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-debugger/dist/debugger.js:1835:52
>     at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:76:1
>     at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1
>     at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:90:1
>     at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1
>     at runSelectEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:698:1)
>     at runEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:435:1)
>     at next (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:315:1)
>     at currCb (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:388:1)
>     at runSelectEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:699:1)
>     at runEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:435:1)
>     at next (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:315:1)
>     at currCb (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:388:1)
>     at runSelectEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:699:1)
>     at runEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:435:1)
>     at next (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:315:1)
>     at currCb (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:388:1)
>     at runSelectEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:699:1)
>     at runEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:435:1)
>     at next (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:315:1)
>     at currCb (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:388:1)
>     at runSelectEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:699:1)
>     at runEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:435:1)
>     at next (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:315:1)
>     at currCb (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:388:1)
>     at runSelectEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:699:1)
>     at runEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:435:1)
>     at next (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:315:1)
>     at proc (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:270:1)
>     at runForkEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:554:1)
>     at runEffect (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:435:1)
>     at next (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:315:1)
>     at currCb (/usr/local/lib/node_modules/truffle/build/webpack:/~/redux-saga/es/internal/proc.js:388:1)
> 
> SimpleStorage.sol:
> 
> 1: pragma solidity ^0.4.18;
> 2:
> 3: contract SimpleStorage {
>    ^^^^^^^^^^^^^^^^^^^^^^^^
> 
> debug(develop:0xf5775c50...)>

### PR DESCRIPTION
**Pull request by gnidan**
Fixes #37 

- Convert indexBy selectors into functions (from objects)
- Add hack to remove potential constructor arguments when searching for index for some CREATE binary
- Add some docs / clean up listener sagas a bit

### CODE REVIEW

File: lib/context/selectors/index.js [hunk 1]
```diff
@@ -83,7 +86,19 @@ const context = createSelectorTree({
     binary: createLeaf(
       [contexts],
 
-      (contexts) => contexts.indexForBinary
+      (contexts) => (
+        (binary) => {
+          // trim off possible constructor args, one word at a time
+          // HACK until there's better CREATE semantics
+          let index = undefined;
+          while (index === undefined && binary) {
```
Comment (cgewecke) [inline lib/context/selectors/index.js]: `binary.length` maybe?

Comment (cgewecke) [reply lib/context/selectors/index.js]: I like this loop.

Comment (gnidan) [reply lib/context/selectors/index.js]: I checked, and empty strings are falsey. I chose this approach in case `binary` is given as null or something.

Comment (cgewecke) [reply lib/context/selectors/index.js]: Yes. Makes sense. I'm getting this in the chrome console:
```javascript
> "" === false
< false
> "" == false
< true
> "x" == true
< false
```

Comment (gnidan) [reply lib/context/selectors/index.js]: I might follow Ben's choice to use Typescript and then you won't have to scold me for being a type-waffler

Comment (cgewecke) [reply lib/context/selectors/index.js]: Oh, but doesn't the above suggest that a string with length isn't inherently 'truthy'.

Comment (gnidan) [reply lib/context/selectors/index.js]: It's truthy, but not true... `while (condition)` means the same thing as `while (!!condition)`; `("x" ? true : false) === true`, e.g.

Comment (cgewecke) [reply lib/context/selectors/index.js]: Ok fine. But if you don't start making mistakes I'm going to stop reviewing your code!!!!

Comment (cgewecke) [reply lib/context/selectors/index.js]: Actually I'm still not convinced. I don't see how "0x606060" can ever evaluate to true:
```javascript
> "0x606060" == true
< false
> "0x606060" === true
< false
```

Comment (seesemichaelj) [reply lib/context/selectors/index.js]: Sorry for my creeping nature, but:
```
if ("0x606060") console.log("hi")
hi
```

Comment (cgewecke) [reply lib/context/selectors/index.js]: Ok I give up.

Comment (seesemichaelj) [reply lib/context/selectors/index.js]: this looks like a cool resource: https://www.sitepoint.com/javascript-truthy-falsy/

but checkout https://javascriptweblog.wordpress.com/2011/02/07/truth-equality-and-javascript/, apparently in `"0x606060" == true`, the string and bool both get typed to numbers and the string ends up being `NaN`

Comment (cgewecke) [reply lib/context/selectors/index.js]: Thanks @seesemichaelj, awesome.

Comment (seesemichaelj) [reply lib/context/selectors/index.js]: I guess if you're ever trying to evaluate truthy status, use conditionals instead of comparisons to true/false because the ECMA standard can cause weird type conversions when using comparisons
